### PR TITLE
Fix memory leak creating new istr objects

### LINKED ISSUE #1131: Memory leak creating istr in multidict 6.3.0,6.3.1,6.3.2
> multidict==6.2.0
> ```bash
> ❯ python test_leak.py
> Initial memory usage: 39.44 MB
> Memory usage: 39.44 MB
> Memory usage: 40.47 MB
> Memory usage: 40.61 MB
> Memory usage: 40.61 MB
> Memory usage: 40.61 MB
> Memory usage: 40.61 MB
> Memory usage: 40.70 MB
> ```
> 
> multidict==6.3.2
> ```bash
> ❯ python .tmp/test_leak.py
> Initial memory usage: 39.00 MB
> Memory usage: 39.00 MB
> Memory usage: 41.25 MB
> Memory usage: 42.12 MB
> Memory usage: 42.95 MB
> Memory usage: 44.38 MB
> Memory usage: 44.77 MB
> Memory usage: 46.06 MB
> Memory usage: 47.27 MB
> Memory usage: 47.84 MB
> Memory usage: 49.34 MB
> ```
> 
> Reproducer
> ```python
> import asyncio
> import os
> 
> import psutil
> from aiohttp import ClientSession, web
> 
> 
> def get_memory_usage():
>     process = psutil.Process(os.getpid())
>     memory_info = process.memory_info()
>     return memory_info.rss / (1024 * 1024)
> 
> 
> async def handle_ping(request):
>     return web.Response(text='pong')
> 
> 
> async def run_server():
>     app = web.Application()
>     app.router.add_get('/ping', handle_ping)
> 
>     runner = web.AppRunner(app)
>     await runner.setup()
>     site = web.TCPSite(runner, 'localhost', 8080)
>     await site.start()
> 
> 
> async def run_client():
>     total_requests = 10_000
>     async with ClientSession() as session:
>         for i in range(total_requests):
>             await make_request(session, i)
> 
> 
> async def make_request(session, request_id):
>     headers = {
>         'Accept': 'text/plain',
>     }
> 
>     async with session.get('http://localhost:8080/ping', headers=headers) as response:
>         await response.text()
> 
> 
> async def memory_monitor():
>     while True:
>         print(f'Memory usage: {get_memory_usage():.2f} MB')
>         await asyncio.sleep(1)
> 
> 
> async def main():
>     asyncio.create_task(memory_monitor())
>     await run_server()
>     await asyncio.sleep(1)  # wait server
>     for _ in range(10_000):
>         await run_client()
> 
> 
> if __name__ == '__main__':
>     asyncio.run(main())
> 
> ```
>  

 _Originally posted by @ermakov-oleg in [#1117](https://github.com/aio-libs/multidict/issues/1117#issuecomment-2787349352)_

### PR DESCRIPTION
**Pull request by bdraco**
Fixes leak 1 from https://github.com/aio-libs/multidict/issues/1131#issuecomment-2787514071 (`IStr_New` path)

see https://github.com/aio-libs/multidict/issues/1131#issuecomment-2787878877 https://github.com/aio-libs/multidict/issues/1131#issuecomment-2787879594 https://github.com/aio-libs/multidict/issues/1131#issuecomment-2787891048

This also seems to fix the perf regression in popitem from https://github.com/aio-libs/multidict/pull/1097#issuecomment-2746161895
https://codspeed.io/aio-libs/multidict/branches/istr-keys

introduced #1097
fixes #1131

### CODE REVIEW

File: multidict/_multilib/istr.h [hunk 1]
```diff
@@ -146,34 +146,11 @@ static PyType_Spec istr_spec = {
...
 IStr_New(mod_state *state, PyObject *str, PyObject *canonical)
 {
-    PyObject *args = NULL;
-    PyObject *kwds = NULL;
-    PyObject *res = NULL;
-
-    args = PyTuple_Pack(1, str);
-    if (args == NULL) {
-        goto ret;
+    PyObject *res = PyObject_Str(str);
```
Comment (bdraco) [inline multidict/_multilib/istr.h:149]: This won't work because we need a new object. Got side tracked and haven't been able to come back to this yet

**Review by asvetlov — APPROVED** [review]
Looks good, thank you!

**Comment by bdraco** [comment]
Thanks for the reviews.

0100 here so I'll get these merged and a release done tomorrow after some 💤
